# Generated by Django 4.2.7 on 2023-11-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
