# Generated by Django 4.2.7 on 2023-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
